-- =====================================================================
-- Phase 2 — venues become dynamic, family-editable data.
-- Run this once in the Supabase SQL editor (Project > SQL Editor).
--
-- Venues are readable by ANYONE (anon + authenticated) since they're the
-- core public content of the site, but only signed-in family members can
-- add/edit/delete them.
-- =====================================================================

create table if not exists public.venues (
  id text primary key,
  slug text not null,
  num text,
  name text not null,
  location text,
  theme text,
  vc text,
  vc_deep text,
  search_term text,
  site_url text,
  site_label text,
  ig_url text,
  ig_label text,
  one_liner text,
  lead text,
  why text,
  note text,
  moods jsonb not null default '[]'::jsonb,
  included jsonb not null default '[]'::jsonb,
  shots jsonb not null default '{}'::jsonb,
  order_index numeric not null default 0,
  created_by uuid references auth.users (id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.venues enable row level security;

create policy "venues are publicly readable"
  on public.venues for select
  to anon, authenticated
  using (true);

create policy "venues writable by signed-in users"
  on public.venues for all
  to authenticated
  using (true) with check (true);

-- ---------------- seed: the original five contenders ----------------
insert into public.venues (id, slug, num, name, location, theme, vc, vc_deep, search_term, site_url, site_label, ig_url, ig_label, one_liner, lead, why, note, moods, included, shots, order_index)
values ('castle', 'castle-farms', 'Venue 01', 'Castle Farms', 'Charlevoix, Michigan', 'Fairytale Castle', 'var(--orchid)', '#5F57C4', 'Castle Farms Charlevoix wedding', 'https://castlefarms.com/weddings/', 'castlefarms.com', 'https://www.instagram.com/castlefarms.weddings/', '@castlefarms.weddings', 'A real French-inspired castle in Northern Michigan — turrets, courtyards, and yes, a dragon.', 'Imagine saying “I do” inside a 1918 stone castle, ringed by formal gardens and Romanesque arches, with all the destination-wedding magic and none of the boarding passes.', 'It delivers fairytale, storybook energy that feels genuinely special — while staying an easy Midwest drive for your guests. Destination feel, hometown logistics.', 'a castle. with a dragon. need we say more?', '["Fairytale","Romantic","Elegant","No Passport"]'::jsonb, '[{"ic":"♟","title":"Five distinct spaces","desc":"Choose from grand halls and garden rooms — King''s Great Hall, the East & West Garden Rooms, the stone Knight''s Castle."},{"ic":"⛩","title":"Courtyard ceremonies","desc":"The Queen''s Courtyard (five soaring stone arches) or Knight''s Courtyard with a gazebo & fountain."},{"ic":"✨","title":"Coordinator + the basics","desc":"A dedicated venue coordinator, tables, chairs, white linens, candle centerpieces, and a bridal dressing suite."},{"ic":"🍽","title":"Bring your own vendors","desc":"Full flexibility to choose your caterer and pros (1918 Cellars house wine is used for wine service)."},{"ic":"👪","title":"Up to ~300 guests","desc":"Rooms scale from intimate micro-weddings to grand 300-guest celebrations."},{"ic":"🐉","title":"A whole estate to roam","desc":"Gardens, the largest outdoor model railroad in Michigan, and a dragon statue to hunt down."}]'::jsonb, '{"arrival":["the stone gatehouse + turrets at golden hour","guests walking the entrance drive","castle reflected in a courtyard fountain","close-up: ivy on the stone walls"],"ceremony":["Queen''s Courtyard arches set with white chairs","aisle view toward the stone arch","ring exchange under the crenellations","garden ceremony detail — florals on stone"],"reception":["King''s Great Hall with iron chandeliers","candlelit tablescape in a garden room","first dance under white chandeliers","French doors open to the courtyard at dusk"],"guest":["cocktail hour in the gardens","guests exploring the castle grounds","kids on the model railroad","bridal suite getting-ready moment"],"area":["downtown Charlevoix waterfront","a Lake Michigan sunset","the famous Mushroom Houses","a winery / boat-day afternoon"],"signature":["the dragon statue — obligatory photo","full castle facade, wide","turret + sky detail","the formal garden in bloom"]}'::jsonb, 1)
on conflict (id) do nothing;
insert into public.venues (id, slug, num, name, location, theme, vc, vc_deep, search_term, site_url, site_label, ig_url, ig_label, one_liner, lead, why, note, moods, included, shots, order_index)
values ('beaches', 'beaches-turks', 'Venue 02', 'Beaches Turks & Caicos', 'Grace Bay, Providenciales', 'Family Vacation Paradise', 'var(--sea)', '#0A8A90', 'Beaches Turks and Caicos wedding Grace Bay', 'https://www.beaches.com/turks-caicos/weddings/', 'beaches.com', 'https://www.instagram.com/beachesresortsweddings/', '@beachesresortsweddings', 'A wedding and a family vacation rolled into one, on the world''s best beach.', 'Picture barefoot vows on 12 miles of powder-white sand, then a week of waterparks, snorkeling and 20-something restaurants so every guest — from toddlers to grandparents — has the trip of their life.', 'It''s the everyone''s-invited option: an all-inclusive resort where the celebration becomes a shared family vacation on legendary Grace Bay.', 'the whole crew, one beach, zero stress', '["Tropical","Family-Friendly","Fun","All-Inclusive"]'::jsonb, '[{"ic":"💒","title":"WeddingMoons packages","desc":"All-inclusive planning, ceremony setup, dining and photography — plus a dedicated wedding planner."},{"ic":"⛱","title":"Ceremony, your way","desc":"Beachfront, an oceanfront gazebo, the Garden of Love, or the Schooner Sunset Wedding Deck."},{"ic":"🍾","title":"Receptions big & small","desc":"From Key West Village to the Pavilion and Ballroom for larger celebrations."},{"ic":"🏊","title":"45,000 sq ft waterpark","desc":"Plus 10 pools, 15 bars, two Red Lane spas and a Kids Camp for infants to teens."},{"ic":"🍴","title":"20+ restaurants","desc":"Truly all-inclusive dining, from fine dining to a beachside jerk shack."},{"ic":"✈","title":"15 min from the airport","desc":"Six themed villages on one easy, walkable resort — short transfer, long memories."}]'::jsonb, '{"arrival":["resort arrival + welcome drink","the turquoise-water first view","a themed village lobby","beach cabana with your names on it"],"ceremony":["barefoot beach ceremony, ocean behind","oceanfront gazebo draped in white","aisle of petals on the sand","sunset vows silhouette"],"reception":["beachside reception, string lights","tablescape with sea-glass tones","dance floor under the stars","sparkler send-off on the sand"],"guest":["the waterpark in full swing","kids at Kids Camp","snorkeling on the reef","grandparents relaxing poolside"],"area":["aerial of Grace Bay''s 12-mile beach","a Providenciales excursion boat","conch shack / local flavor","a Caribbean sunset cruise"],"signature":["that impossibly turquoise water","the swim-up bar","whole-family group shot on the beach","Grace Bay from above"]}'::jsonb, 2)
on conflict (id) do nothing;
insert into public.venues (id, slug, num, name, location, theme, vc, vc_deep, search_term, site_url, site_label, ig_url, ig_label, one_liner, lead, why, note, moods, included, shots, order_index)
values ('hyatt', 'hyatt-aruba', 'Venue 03', 'Hyatt Regency Aruba', 'Palm Beach, Aruba', 'Elegant Tropical Escape', 'var(--coral)', '#E84C3B', 'Hyatt Regency Aruba wedding Palm Beach', 'https://www.hyatt.com/hyatt-regency/en-US/auaru-hyatt-regency-aruba-resort-spa-and-casino', 'hyatt.com', 'https://www.instagram.com/hyattregencyaruba/', '@hyattregencyaruba', 'Upscale, sunset-soaked, and effortlessly tropical — polished without the stiffness.', 'On Aruba''s glamorous Palm Beach, swaying palms and lagoon pools set the scene for sunset ceremonies and refined receptions — the grown-up tropical wedding that still feels like a holiday.', 'It threads the needle: a genuinely upscale beachfront resort that stays relaxed and warm rather than formal. Sophistication with sand between your toes.', 'sunsets here are basically showing off', '["Elegant","Sunset","Luxury","Tropical"]'::jsonb, '[{"ic":"🌅","title":"Sunset beach ceremonies","desc":"Palm Beach faces west — ceremonies time out to a glowing Caribbean sunset backdrop."},{"ic":"🌴","title":"Lush 12-acre grounds","desc":"Multi-level lagoon pools, gardens and a stretch of Aruba''s calmest, prettiest beach."},{"ic":"🥂","title":"Ballroom + open-air spaces","desc":"Elegant indoor ballrooms and breezy oceanfront terraces for receptions of any size."},{"ic":"👸","title":"On-site wedding team","desc":"Dedicated coordinators and customizable packages handle catering, decor and the day-of flow."},{"ic":"🍸","title":"Dining, spa & casino","desc":"Multiple restaurants, a full-service spa, and the on-site Stellaris casino for the night owls."},{"ic":"☀","title":"“One Happy Island” weather","desc":"Aruba sits below the hurricane belt — reliably sunny, perfect for a fall 2028 date."}]'::jsonb, '{"arrival":["resort entrance + palm-lined drive","lagoon pool first impression","oceanfront lobby view","welcome detail on Palm Beach"],"ceremony":["beachfront ceremony at sunset","arch framing the horizon","aisle toward the sea","exchanging rings, golden light"],"reception":["elegant ballroom tablescape","oceanfront terrace dinner","candlelit lounge area","band / dance floor glamour"],"guest":["palapa loungers on Palm Beach","spa relaxation moment","Stellaris casino night","catamaran day trip"],"area":["Palm Beach high-rise strip at dusk","California Lighthouse","Aruba''s desert + divi-divi trees","a vibrant local sunset bar"],"signature":["the signature Aruba sunset","palms against the sky","lagoon pool aerial","toes-in-sand cocktail hour"]}'::jsonb, 3)
on conflict (id) do nothing;
insert into public.venues (id, slug, num, name, location, theme, vc, vc_deep, search_term, site_url, site_label, ig_url, ig_label, one_liner, lead, why, note, moods, included, shots, order_index)
values ('greatwolf', 'great-wolf', 'Venue 04', 'Great Wolf Lodge', 'Sandusky, Ohio', 'Unexpectedly Fun', 'var(--palm)', '#2C8552', 'Great Wolf Lodge Sandusky wedding event', 'https://www.greatwolf.com/sandusky', 'greatwolf.com/sandusky', 'https://www.instagram.com/greatwolflodge/', '@greatwolflodge', 'The wildcard. A wedding that doubles as the most legendary family weekend ever.', 'Hear us out: a cozy north-woods lodge, an indoor waterpark, and a wedding nobody will ever stop talking about. It''s the option with the best story — and we''re leaning all the way in.', 'Pure joy and zero pretension. The kids (and let''s be honest, the adults) get a waterpark; you get a celebration with a one-of-a-kind story. The fun is the feature.', 'yes we''re serious. yes there''s a waterpark. it RULES.', '["Fun","Family-Focused","Playful","Memorable"]'::jsonb, '[{"ic":"🐺","title":"North-woods lodge vibe","desc":"A warm timber-and-stone great room with a towering fireplace — cabin-cozy, crowd-friendly."},{"ic":"🏞","title":"Event & conference space","desc":"Flexible banquet rooms for the ceremony and reception, with on-site event staff."},{"ic":"🌊","title":"Indoor waterpark","desc":"A giant climate-controlled waterpark — weatherproof entertainment for every guest, all weekend."},{"ic":"🏨","title":"Everyone stays on-site","desc":"Suites for the whole party means the celebration never really stops."},{"ic":"🎳","title":"Endless activities","desc":"Ropes course, mini-golf, arcade, bowling and a spa — nobody is ever bored."},{"ic":"🚗","title":"Easy + drivable","desc":"In Sandusky near Cedar Point — an accessible road-trip weekend, no flights required."}]'::jsonb, '{"arrival":["the grand timber lodge entrance","the great-room fireplace","wolf-ear hoodies group shot","check-in welcome moment"],"ceremony":["banquet-room ceremony, dressed up","aisle with a rustic-lodge backdrop","vows + a wink of whimsy","ring shot, cozy lighting"],"reception":["ballroom reception, warm lighting","tablescape with woodland greens","first dance, full dancefloor","late-night dessert spread"],"guest":["the waterpark wave pool","kids on the waterslides","arcade / bowling fun","ropes course adventure"],"area":["Cedar Point coaster skyline","Lake Erie shoreline","Sandusky bay sunset","a classic Ohio road-trip stop"],"signature":["the iconic waterpark hero shot","wolf ears + wedding attire","the giant fireplace portrait","everyone in the wave pool"]}'::jsonb, 4)
on conflict (id) do nothing;
insert into public.venues (id, slug, num, name, location, theme, vc, vc_deep, search_term, site_url, site_label, ig_url, ig_label, one_liner, lead, why, note, moods, included, shots, order_index)
values ('sandos', 'sandos-finisterra', 'Venue 05', 'Sandos Finisterra', 'Cabo San Lucas, Mexico', 'Clifftop Adventure', 'var(--sun)', '#D6912A', 'Sandos Finisterra Cabo San Lucas wedding', 'https://www.sandos.com/sandos-finisterra/los-cabos-all-inclusive-resort', 'sandos.com', 'https://www.instagram.com/sandosfinisterra/', '@sandosfinisterra', '“The End of the Earth” — a dramatic clifftop perch where the desert meets the Pacific.', 'Set on a cliff at the very tip of the Baja Peninsula by the Land''s End Arch, Finisterra trades Caribbean calm for big Pacific drama: golden beaches, mountaintop terraces, and sunsets that feel cinematic.', 'A boldly different destination than the Caribbean picks — rugged, panoramic, adventurous — with downtown Cabo and the marina just a stroll away.', 'sunsets at the end of the earth. iconic.', '["Adventure","Sunset","Ocean Views","Luxury"]'::jsonb, '[{"ic":"🌋","title":"Three dramatic venues","desc":"Beachfront, a desert garden, or the panoramic mountaintop terrace overlooking Cabo."},{"ic":"🏖","title":"7 acres of golden beach","desc":"A sweeping Pacific shoreline (gorgeous for ceremonies & photos) right by Land''s End."},{"ic":"🎁","title":"“Dreamcatcher” packages","desc":"All-inclusive: cake, flowers, setup, photography and a dedicated wedding team."},{"ic":"🍹","title":"All-inclusive resort fun","desc":"Three pools (incl. an adults-only swim-up bar), a mountainside spa, and nightly entertainment."},{"ic":"🐫","title":"Adventure on tap","desc":"Sea-turtle swims, camel safaris, sailing, yacht cruises and tequila tastings for your guests."},{"ic":"🌊","title":"Two seas, one view","desc":"Where the Pacific meets the Sea of Cortés — panoramic vistas from nearly everywhere."}]'::jsonb, '{"arrival":["clifftop resort first view","the Land''s End Arch from the beach","lobby framing the Pacific","welcome margarita moment"],"ceremony":["beach ceremony, Pacific waves behind","mountaintop terrace at sunset","aisle toward the ocean","desert-garden ceremony detail"],"reception":["clifftop terrace dinner at dusk","tablescape in warm amber tones","dancing with the bay lit up below","sparklers over the Pacific"],"guest":["adults-only swim-up bar","a sunset catamaran cruise","downtown Cabo marina night","spa del Mar relaxation"],"area":["Land''s End Arch & rock formations","Cabo marina + yachts","the Baja desert landscape","a dramatic Pacific sunset"],"signature":["the Arch at golden hour","clifftop panorama, wide","sun dropping into the Pacific","desert-meets-ocean hero shot"]}'::jsonb, 5)
on conflict (id) do nothing;
