/* =====================================================================
   Venue + timeline data for Gabrielle & Kris. Exposed as window.WED.
   ===================================================================== */
window.WED = {
  couple: "Gabrielle & Kris",
  window: "August – December 2028",

  timeline: [
    { n:"Phase 01", title:"Dreaming & Exploring", when:"Now – Summer 2026", color:"var(--sky)", key:true,
      items:["Local or destination?","What kind of experience excites us?","Big party or small & cozy?","What atmosphere feels like *us*?"] },
    { n:"Phase 02", title:"Choosing the Destination", when:"Fall 2026 – Summer 2027", color:"var(--orchid)",
      items:["Pick the destination","Pick the venue","Rough guest-count range","Preferred wedding season"] },
    { n:"Phase 03", title:"Building the Wedding", when:"Late 2027", color:"var(--sea)",
      items:["Wedding party","Travel plans","Guest communication","Photographer & decor direction"] },
    { n:"Phase 04", title:"Final Details", when:"Early 2028", color:"var(--palm)",
      items:["Final guest count","Logistics & timeline","Reception details","Last little touches"] },
    { n:"Phase 05", title:"Wedding Time!", when:"Aug – Dec 2028", color:"var(--coral)",
      items:["Show up","Marry your person","Dance till late","Celebrate 🎉"] },
  ],

  galleryCats: [
    { key:"arrival",   gn:"Gallery 01", title:"Arrival & First Impressions", q:"What does it feel like when guests arrive?" },
    { key:"ceremony",  gn:"Gallery 02", title:"Ceremony Inspiration",        q:"What does the ceremony feel like?" },
    { key:"reception", gn:"Gallery 03", title:"Reception Inspiration",       q:"What does the celebration feel like?" },
    { key:"guest",     gn:"Gallery 04", title:"Guest Experience",            q:"What does the whole weekend feel like?" },
    { key:"area",      gn:"Gallery 05", title:"The Surrounding Area",        q:"What's the broader destination like?" },
    { key:"signature", gn:"Gallery 06", title:"Signature Moments",           q:"What makes this place unmistakably itself?" },
  ],

  venues: [
    {
      id:"castle", slug:"castle-farms", num:"Venue 01",
      name:"Castle Farms", location:"Charlevoix, Michigan",
      theme:"Fairytale Castle", vc:"var(--orchid)", vcDeep:"#5F57C4",
      searchTerm:"Castle Farms Charlevoix wedding",
      sources:{ site:"https://castlefarms.com/weddings/", siteLabel:"castlefarms.com", ig:"https://www.instagram.com/castlefarms.weddings/", igLabel:"@castlefarms.weddings" },
      moods:["Fairytale","Romantic","Elegant","No Passport"],
      oneLiner:"A real French-inspired castle in Northern Michigan — turrets, courtyards, and yes, a dragon.",
      lead:"Imagine saying \u201cI do\u201d inside a 1918 stone castle, ringed by formal gardens and Romanesque arches, with all the destination-wedding magic and none of the boarding passes.",
      why:"It delivers fairytale, storybook energy that feels genuinely special \u2014 while staying an easy Midwest drive for your guests. Destination feel, hometown logistics.",
      note:"a castle. with a dragon. need we say more?",
      included:[
        {ic:"\u265F",title:"Five distinct spaces",desc:"Choose from grand halls and garden rooms \u2014 King's Great Hall, the East & West Garden Rooms, the stone Knight's Castle."},
        {ic:"\u26E9",title:"Courtyard ceremonies",desc:"The Queen's Courtyard (five soaring stone arches) or Knight's Courtyard with a gazebo & fountain."},
        {ic:"\u2728",title:"Coordinator + the basics",desc:"A dedicated venue coordinator, tables, chairs, white linens, candle centerpieces, and a bridal dressing suite."},
        {ic:"\u{1F37D}",title:"Bring your own vendors",desc:"Full flexibility to choose your caterer and pros (1918 Cellars house wine is used for wine service)."},
        {ic:"\u{1F46A}",title:"Up to ~300 guests",desc:"Rooms scale from intimate micro-weddings to grand 300-guest celebrations."},
        {ic:"\u{1F409}",title:"A whole estate to roam",desc:"Gardens, the largest outdoor model railroad in Michigan, and a dragon statue to hunt down."},
      ],
      shots:{
        arrival:["the stone gatehouse + turrets at golden hour","guests walking the entrance drive","castle reflected in a courtyard fountain","close-up: ivy on the stone walls"],
        ceremony:["Queen's Courtyard arches set with white chairs","aisle view toward the stone arch","ring exchange under the crenellations","garden ceremony detail \u2014 florals on stone"],
        reception:["King's Great Hall with iron chandeliers","candlelit tablescape in a garden room","first dance under white chandeliers","French doors open to the courtyard at dusk"],
        guest:["cocktail hour in the gardens","guests exploring the castle grounds","kids on the model railroad","bridal suite getting-ready moment"],
        area:["downtown Charlevoix waterfront","a Lake Michigan sunset","the famous Mushroom Houses","a winery / boat-day afternoon"],
        signature:["the dragon statue \u2014 obligatory photo","full castle facade, wide","turret + sky detail","the formal garden in bloom"],
      },
    },
    {
      id:"beaches", slug:"beaches-turks", num:"Venue 02",
      name:"Beaches Turks & Caicos", location:"Grace Bay, Providenciales",
      theme:"Family Vacation Paradise", vc:"var(--sea)", vcDeep:"#0A8A90",
      searchTerm:"Beaches Turks and Caicos wedding Grace Bay",
      sources:{ site:"https://www.beaches.com/turks-caicos/weddings/", siteLabel:"beaches.com", ig:"https://www.instagram.com/beachesresortsweddings/", igLabel:"@beachesresortsweddings" },
      moods:["Tropical","Family-Friendly","Fun","All-Inclusive"],
      oneLiner:"A wedding and a family vacation rolled into one, on the world's best beach.",
      lead:"Picture barefoot vows on 12 miles of powder-white sand, then a week of waterparks, snorkeling and 20-something restaurants so every guest \u2014 from toddlers to grandparents \u2014 has the trip of their life.",
      why:"It's the everyone's-invited option: an all-inclusive resort where the celebration becomes a shared family vacation on legendary Grace Bay.",
      note:"the whole crew, one beach, zero stress",
      included:[
        {ic:"\u{1F492}",title:"WeddingMoons packages",desc:"All-inclusive planning, ceremony setup, dining and photography \u2014 plus a dedicated wedding planner."},
        {ic:"\u26F1",title:"Ceremony, your way",desc:"Beachfront, an oceanfront gazebo, the Garden of Love, or the Schooner Sunset Wedding Deck."},
        {ic:"\u{1F37E}",title:"Receptions big & small",desc:"From Key West Village to the Pavilion and Ballroom for larger celebrations."},
        {ic:"\u{1F3CA}",title:"45,000 sq ft waterpark",desc:"Plus 10 pools, 15 bars, two Red Lane spas and a Kids Camp for infants to teens."},
        {ic:"\u{1F374}",title:"20+ restaurants",desc:"Truly all-inclusive dining, from fine dining to a beachside jerk shack."},
        {ic:"\u2708",title:"15 min from the airport",desc:"Six themed villages on one easy, walkable resort \u2014 short transfer, long memories."},
      ],
      shots:{
        arrival:["resort arrival + welcome drink","the turquoise-water first view","a themed village lobby","beach cabana with your names on it"],
        ceremony:["barefoot beach ceremony, ocean behind","oceanfront gazebo draped in white","aisle of petals on the sand","sunset vows silhouette"],
        reception:["beachside reception, string lights","tablescape with sea-glass tones","dance floor under the stars","sparkler send-off on the sand"],
        guest:["the waterpark in full swing","kids at Kids Camp","snorkeling on the reef","grandparents relaxing poolside"],
        area:["aerial of Grace Bay's 12-mile beach","a Providenciales excursion boat","conch shack / local flavor","a Caribbean sunset cruise"],
        signature:["that impossibly turquoise water","the swim-up bar","whole-family group shot on the beach","Grace Bay from above"],
      },
    },
    {
      id:"hyatt", slug:"hyatt-aruba", num:"Venue 03",
      name:"Hyatt Regency Aruba", location:"Palm Beach, Aruba",
      theme:"Elegant Tropical Escape", vc:"var(--coral)", vcDeep:"#E84C3B",
      searchTerm:"Hyatt Regency Aruba wedding Palm Beach",
      sources:{ site:"https://www.hyatt.com/hyatt-regency/en-US/auaru-hyatt-regency-aruba-resort-spa-and-casino", siteLabel:"hyatt.com", ig:"https://www.instagram.com/hyattregencyaruba/", igLabel:"@hyattregencyaruba" },
      moods:["Elegant","Sunset","Luxury","Tropical"],
      oneLiner:"Upscale, sunset-soaked, and effortlessly tropical \u2014 polished without the stiffness.",
      lead:"On Aruba's glamorous Palm Beach, swaying palms and lagoon pools set the scene for sunset ceremonies and refined receptions \u2014 the grown-up tropical wedding that still feels like a holiday.",
      why:"It threads the needle: a genuinely upscale beachfront resort that stays relaxed and warm rather than formal. Sophistication with sand between your toes.",
      note:"sunsets here are basically showing off",
      included:[
        {ic:"\u{1F305}",title:"Sunset beach ceremonies",desc:"Palm Beach faces west \u2014 ceremonies time out to a glowing Caribbean sunset backdrop."},
        {ic:"\u{1F334}",title:"Lush 12-acre grounds",desc:"Multi-level lagoon pools, gardens and a stretch of Aruba's calmest, prettiest beach."},
        {ic:"\u{1F942}",title:"Ballroom + open-air spaces",desc:"Elegant indoor ballrooms and breezy oceanfront terraces for receptions of any size."},
        {ic:"\u{1F478}",title:"On-site wedding team",desc:"Dedicated coordinators and customizable packages handle catering, decor and the day-of flow."},
        {ic:"\u{1F378}",title:"Dining, spa & casino",desc:"Multiple restaurants, a full-service spa, and the on-site Stellaris casino for the night owls."},
        {ic:"\u2600",title:"\u201cOne Happy Island\u201d weather",desc:"Aruba sits below the hurricane belt \u2014 reliably sunny, perfect for a fall 2028 date."},
      ],
      shots:{
        arrival:["resort entrance + palm-lined drive","lagoon pool first impression","oceanfront lobby view","welcome detail on Palm Beach"],
        ceremony:["beachfront ceremony at sunset","arch framing the horizon","aisle toward the sea","exchanging rings, golden light"],
        reception:["elegant ballroom tablescape","oceanfront terrace dinner","candlelit lounge area","band / dance floor glamour"],
        guest:["palapa loungers on Palm Beach","spa relaxation moment","Stellaris casino night","catamaran day trip"],
        area:["Palm Beach high-rise strip at dusk","California Lighthouse","Aruba's desert + divi-divi trees","a vibrant local sunset bar"],
        signature:["the signature Aruba sunset","palms against the sky","lagoon pool aerial","toes-in-sand cocktail hour"],
      },
    },
    {
      id:"greatwolf", slug:"great-wolf", num:"Venue 04",
      name:"Great Wolf Lodge", location:"Sandusky, Ohio",
      theme:"Unexpectedly Fun", vc:"var(--palm)", vcDeep:"#2C8552",
      searchTerm:"Great Wolf Lodge Sandusky wedding event",
      sources:{ site:"https://www.greatwolf.com/sandusky", siteLabel:"greatwolf.com/sandusky", ig:"https://www.instagram.com/greatwolflodge/", igLabel:"@greatwolflodge" },
      moods:["Fun","Family-Focused","Playful","Memorable"],
      oneLiner:"The wildcard. A wedding that doubles as the most legendary family weekend ever.",
      lead:"Hear us out: a cozy north-woods lodge, an indoor waterpark, and a wedding nobody will ever stop talking about. It's the option with the best story \u2014 and we're leaning all the way in.",
      why:"Pure joy and zero pretension. The kids (and let's be honest, the adults) get a waterpark; you get a celebration with a one-of-a-kind story. The fun is the feature.",
      note:"yes we're serious. yes there's a waterpark. it RULES.",
      included:[
        {ic:"\u{1F43A}",title:"North-woods lodge vibe",desc:"A warm timber-and-stone great room with a towering fireplace \u2014 cabin-cozy, crowd-friendly."},
        {ic:"\u{1F3DE}",title:"Event & conference space",desc:"Flexible banquet rooms for the ceremony and reception, with on-site event staff."},
        {ic:"\u{1F30A}",title:"Indoor waterpark",desc:"A giant climate-controlled waterpark \u2014 weatherproof entertainment for every guest, all weekend."},
        {ic:"\u{1F3E8}",title:"Everyone stays on-site",desc:"Suites for the whole party means the celebration never really stops."},
        {ic:"\u{1F3B3}",title:"Endless activities",desc:"Ropes course, mini-golf, arcade, bowling and a spa \u2014 nobody is ever bored."},
        {ic:"\u{1F697}",title:"Easy + drivable",desc:"In Sandusky near Cedar Point \u2014 an accessible road-trip weekend, no flights required."},
      ],
      shots:{
        arrival:["the grand timber lodge entrance","the great-room fireplace","wolf-ear hoodies group shot","check-in welcome moment"],
        ceremony:["banquet-room ceremony, dressed up","aisle with a rustic-lodge backdrop","vows + a wink of whimsy","ring shot, cozy lighting"],
        reception:["ballroom reception, warm lighting","tablescape with woodland greens","first dance, full dancefloor","late-night dessert spread"],
        guest:["the waterpark wave pool","kids on the waterslides","arcade / bowling fun","ropes course adventure"],
        area:["Cedar Point coaster skyline","Lake Erie shoreline","Sandusky bay sunset","a classic Ohio road-trip stop"],
        signature:["the iconic waterpark hero shot","wolf ears + wedding attire","the giant fireplace portrait","everyone in the wave pool"],
      },
    },
    {
      id:"sandos", slug:"sandos-finisterra", num:"Venue 05",
      name:"Sandos Finisterra", location:"Cabo San Lucas, Mexico",
      theme:"Clifftop Adventure", vc:"var(--sun)", vcDeep:"#D6912A",
      searchTerm:"Sandos Finisterra Cabo San Lucas wedding",
      sources:{ site:"https://www.sandos.com/sandos-finisterra/los-cabos-all-inclusive-resort", siteLabel:"sandos.com", ig:"https://www.instagram.com/sandosfinisterra/", igLabel:"@sandosfinisterra" },
      moods:["Adventure","Sunset","Ocean Views","Luxury"],
      oneLiner:"\u201cThe End of the Earth\u201d \u2014 a dramatic clifftop perch where the desert meets the Pacific.",
      lead:"Set on a cliff at the very tip of the Baja Peninsula by the Land's End Arch, Finisterra trades Caribbean calm for big Pacific drama: golden beaches, mountaintop terraces, and sunsets that feel cinematic.",
      why:"A boldly different destination than the Caribbean picks \u2014 rugged, panoramic, adventurous \u2014 with downtown Cabo and the marina just a stroll away.",
      note:"sunsets at the end of the earth. iconic.",
      included:[
        {ic:"\u{1F30B}",title:"Three dramatic venues",desc:"Beachfront, a desert garden, or the panoramic mountaintop terrace overlooking Cabo."},
        {ic:"\u{1F3D6}",title:"7 acres of golden beach",desc:"A sweeping Pacific shoreline (gorgeous for ceremonies & photos) right by Land's End."},
        {ic:"\u{1F381}",title:"\u201cDreamcatcher\u201d packages",desc:"All-inclusive: cake, flowers, setup, photography and a dedicated wedding team."},
        {ic:"\u{1F379}",title:"All-inclusive resort fun",desc:"Three pools (incl. an adults-only swim-up bar), a mountainside spa, and nightly entertainment."},
        {ic:"\u{1F42B}",title:"Adventure on tap",desc:"Sea-turtle swims, camel safaris, sailing, yacht cruises and tequila tastings for your guests."},
        {ic:"\u{1F30A}",title:"Two seas, one view",desc:"Where the Pacific meets the Sea of Cort\u00e9s \u2014 panoramic vistas from nearly everywhere."},
      ],
      shots:{
        arrival:["clifftop resort first view","the Land's End Arch from the beach","lobby framing the Pacific","welcome margarita moment"],
        ceremony:["beach ceremony, Pacific waves behind","mountaintop terrace at sunset","aisle toward the ocean","desert-garden ceremony detail"],
        reception:["clifftop terrace dinner at dusk","tablescape in warm amber tones","dancing with the bay lit up below","sparklers over the Pacific"],
        guest:["adults-only swim-up bar","a sunset catamaran cruise","downtown Cabo marina night","spa del Mar relaxation"],
        area:["Land's End Arch & rock formations","Cabo marina + yachts","the Baja desert landscape","a dramatic Pacific sunset"],
        signature:["the Arch at golden hour","clifftop panorama, wide","sun dropping into the Pacific","desert-meets-ocean hero shot"],
      },
    },
  ],
};
